import {createServerFn} from "@tanstack/react-start";import{z}from"zod";import{addMemory,readProjectMemory,removeMemory,searchProjectMemory,upsertMemory,type MemoryKind,type ProjectMemoryItem}from"./omnifrog/memory.server";
async function guard(){const{requireSession}=await import("./omnifrog/session.server");await requireSession()}
async function load(id:string){const{selectProject}=await import("./omnifrog/projects.server");const r=await selectProject(id);if(!r)throw new Error("Project not found.");return r}
async function save(id:string,s:ReturnType<typeof readProjectMemory>){const{updateProjectBuildState}=await import("./omnifrog/projects.server");await updateProjectBuildState(id,{projectMemory:s as never});return s}
const kinds=z.enum(["requirement","decision","constraint","architecture","file","agent","checkpoint","error","note"]);
export const getProjectMemory=createServerFn({method:"GET"}).inputValidator((i:{id:string})=>{if(!i?.id)throw new Error("Invalid project.");return{id:i.id}}).handler(async({data})=>{await guard();const p=await load(data.id);return readProjectMemory(p.project.buildState)});
export const addProjectMemory=createServerFn({method:"POST"}).inputValidator((i:{id:string;kind:string;title:string;content:string;tags?:string[];importance?:number;source?:string})=>{if(!i?.id||!kinds.safeParse(i.kind).success||!i.title?.trim()||!i.content?.trim())throw new Error("Invalid memory.");return{id:i.id,kind:i.kind as MemoryKind,title:i.title.trim(),content:i.content.trim(),tags:i.tags??[],importance:i.importance??50,source:i.source??"user"}}).handler(async({data})=>{await guard();const p=await load(data.id);return save(data.id,addMemory(readProjectMemory(p.project.buildState),data))});
export const updateProjectMemory=createServerFn({method:"POST"}).inputValidator((i:{id:string;item:ProjectMemoryItem})=>{if(!i?.id||!i.item?.id||!i.item.title||!i.item.content)throw new Error("Invalid memory.");return i}).handler(async({data})=>{await guard();const p=await load(data.id);return save(data.id,upsertMemory(readProjectMemory(p.project.buildState),data.item))});
export const deleteProjectMemory=createServerFn({method:"POST"}).inputValidator((i:{id:string;memoryId:string})=>{if(!i?.id||!i.memoryId)throw new Error("Invalid memory.");return i}).handler(async({data})=>{await guard();const p=await load(data.id);return save(data.id,removeMemory(readProjectMemory(p.project.buildState),data.memoryId))});
export const searchMemory=createServerFn({method:"POST"}).inputValidator((i:{id:string;query:string;limit?:number})=>({id:i.id,query:i.query??"",limit:Math.min(30,Math.max(1,i.limit??12))})).handler(async({data})=>{await guard();const p=await load(data.id);return searchProjectMemory(readProjectMemory(p.project.buildState),data.query,data.limit)});
