import type { JsonValue } from "./types";
export type MemoryKind="requirement"|"decision"|"constraint"|"architecture"|"file"|"agent"|"checkpoint"|"error"|"note";
export interface ProjectMemoryItem{id:string;kind:MemoryKind;title:string;content:string;tags:string[];importance:number;source:string;createdAt:string;updatedAt:string}
export interface ProjectMemoryState{version:1;items:ProjectMemoryItem[];summary:string;updatedAt:string}
const MAX_ITEMS=20000,MAX_ITEM_CHARS=200000,MAX_SUMMARY_CHARS=500000;
const clean=(v:string,m:number)=>v.replace(/\u0000/g,"").trim().slice(0,m);
const normalize=(x:ProjectMemoryItem):ProjectMemoryItem=>({...x,title:clean(x.title,180),content:clean(x.content,MAX_ITEM_CHARS),tags:[...new Set(x.tags.map(v=>clean(v,50).toLowerCase()).filter(Boolean))].slice(0,200),importance:Math.max(0,Math.min(100,Number(x.importance)||0))});
export function emptyProjectMemory():ProjectMemoryState{return{version:1,items:[],summary:"",updatedAt:new Date().toISOString()}}
export function readProjectMemory(bs:Record<string,JsonValue>):ProjectMemoryState{const raw=bs.projectMemory;if(!raw||typeof raw!=="object"||Array.isArray(raw))return emptyProjectMemory();const v=raw as Record<string,JsonValue>;const arr=Array.isArray(v.items)?v.items:[];return{version:1,items:arr.filter((x):x is Record<string,JsonValue>=>!!x&&typeof x==="object"&&!Array.isArray(x)).map(x=>normalize({id:String(x.id??crypto.randomUUID()),kind:(["requirement","decision","constraint","architecture","file","agent","checkpoint","error","note"].includes(String(x.kind))?String(x.kind):"note") as MemoryKind,title:String(x.title??""),content:String(x.content??""),tags:Array.isArray(x.tags)?x.tags.map(String):[],importance:Number(x.importance??50),source:String(x.source??"unknown"),createdAt:String(x.createdAt??new Date().toISOString()),updatedAt:String(x.updatedAt??new Date().toISOString())})).slice(0,MAX_ITEMS),summary:clean(String(v.summary??""),MAX_SUMMARY_CHARS),updatedAt:String(v.updatedAt??new Date().toISOString())}}
export function addMemory(s:ProjectMemoryState,input:Omit<ProjectMemoryItem,"id"|"createdAt"|"updatedAt">):ProjectMemoryState{const now=new Date().toISOString();const item=normalize({...input,id:crypto.randomUUID(),createdAt:now,updatedAt:now});return{...s,items:[item,...s.items].slice(0,MAX_ITEMS),updatedAt:now}}
export function upsertMemory(s:ProjectMemoryState,item:ProjectMemoryItem):ProjectMemoryState{const n=normalize({...item,updatedAt:new Date().toISOString()});return{...s,items:[n,...s.items.filter(x=>x.id!==n.id)].slice(0,MAX_ITEMS),updatedAt:n.updatedAt}}
export function removeMemory(s:ProjectMemoryState,id:string):ProjectMemoryState{return{...s,items:s.items.filter(x=>x.id!==id),updatedAt:new Date().toISOString()}}
function tokens(t:string){return new Set(t.toLowerCase().replace(/[^\p{L}\p{N}_-]+/gu," ").split(/\s+/).filter(x=>x.length>2))}
export function searchProjectMemory(s:ProjectMemoryState,q:string,limit=12){const terms=tokens(q);return s.items.map(item=>{const h=tokens([item.title,item.content,...item.tags].join(" "));let score=item.importance*.01;for(const t of terms)if(h.has(t))score+=3;return{item,score}}).sort((a,b)=>b.score-a.score||b.item.updatedAt.localeCompare(a.item.updatedAt)).slice(0,limit).map(x=>x.item)}
export function buildMemoryContext(items:ProjectMemoryItem[],maxChars=500000){let out="";for(const i of items){const b="["+i.kind+"] "+i.title+"\n"+i.content+"\nTags: "+i.tags.join(", ")+"\n\n";if(out.length+b.length>maxChars)break;out+=b}return out.trim()}
